#!/usr/bin/env bash
set -euo pipefail

NGINX_SITE="${1:-/etc/nginx/sites-available/hextyl.conf}"
REALIP_SNIPPET="/etc/nginx/snippets/hextyl-cloudflare-realip.conf"
ORIGIN_LOCK_SNIPPET="/etc/nginx/snippets/hextyl-cloudflare-origin-lock.conf"
HEADER_GUARD_SNIPPET="/etc/nginx/snippets/hextyl-cloudflare-header-guard.conf"
WINGS_REMOTE_SNIPPET="/etc/nginx/snippets/hextyl-wings-remote-allow.conf"
NFT_LOCK_FILE="/etc/nftables.d/hextyl-cloudflare-origin-lock.nft"
EXTRA_ALLOW_CSV="${HEXTYL_ORIGIN_EXTRA_ALLOW:-}"
WINGS_ALLOW_CSV="${HEXTYL_WINGS_PANEL_ALLOW:-}"
ENABLE_CF_HEADER_GUARD="${HEXTYL_ENABLE_CF_HEADER_GUARD:-n}"

log() { echo "[INFO] $*"; }
die() { echo "[ERROR] $*" >&2; exit 1; }

[[ "${EUID}" -eq 0 ]] || die "Run as root."
[[ -f "${NGINX_SITE}" ]] || die "Nginx site not found: ${NGINX_SITE}"

command -v curl >/dev/null 2>&1 || die "curl not installed."
command -v nginx >/dev/null 2>&1 || die "nginx not installed."
command -v nft >/dev/null 2>&1 || die "nft not installed."

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

CF_V4="${TMP_DIR}/cf-v4.txt"
CF_V6="${TMP_DIR}/cf-v6.txt"

log "Fetching Cloudflare IP ranges..."
curl -fsSL "https://www.cloudflare.com/ips-v4" -o "${CF_V4}"
curl -fsSL "https://www.cloudflare.com/ips-v6" -o "${CF_V6}"

[[ -s "${CF_V4}" ]] || die "Cloudflare IPv4 list is empty."
[[ -s "${CF_V6}" ]] || die "Cloudflare IPv6 list is empty."

install -d -m 755 /etc/nginx/snippets

{
    echo "# Auto-generated by lock_origin_to_cloudflare.sh"
    echo "real_ip_header CF-Connecting-IP;"
    echo "real_ip_recursive on;"
    while IFS= read -r ip; do
        [[ -n "${ip}" ]] || continue
        echo "set_real_ip_from ${ip};"
    done < "${CF_V4}"
    while IFS= read -r ip; do
        [[ -n "${ip}" ]] || continue
        echo "set_real_ip_from ${ip};"
    done < "${CF_V6}"
} > "${REALIP_SNIPPET}"

{
    echo "# Auto-generated by lock_origin_to_cloudflare.sh"
    echo "allow 127.0.0.1;"
    echo "allow ::1;"
    while IFS= read -r ip; do
        [[ -n "${ip}" ]] || continue
        echo "allow ${ip};"
    done < "${CF_V4}"
    while IFS= read -r ip; do
        [[ -n "${ip}" ]] || continue
        echo "allow ${ip};"
    done < "${CF_V6}"

    if [[ -n "${EXTRA_ALLOW_CSV}" ]]; then
        IFS=',' read -r -a extra <<< "${EXTRA_ALLOW_CSV}"
        for entry in "${extra[@]}"; do
            entry="$(echo "${entry}" | xargs)"
            [[ -n "${entry}" ]] || continue
            echo "allow ${entry};"
        done
    fi

    echo "deny all;"
} > "${ORIGIN_LOCK_SNIPPET}"

{
    echo "# Auto-generated by lock_origin_to_cloudflare.sh"
    echo "location ^~ /api/remote/ {"
    echo "    allow 127.0.0.1;"
    echo "    allow ::1;"
    if [[ -n "${WINGS_ALLOW_CSV}" ]]; then
        IFS=',' read -r -a wings_allow <<< "${WINGS_ALLOW_CSV}"
        for entry in "${wings_allow[@]}"; do
            entry="$(echo "${entry}" | xargs)"
            [[ -n "${entry}" ]] || continue
            echo "    allow ${entry};"
        done
    fi
    echo "    deny all;"
    echo "    try_files \$uri \$uri/ /index.php?\$query_string;"
    echo "}"
} > "${WINGS_REMOTE_SNIPPET}"

ensure_include_once() {
    local include_line="$1"
    grep -Fq "${include_line}" "${NGINX_SITE}" || sed -i "/server_name .*;/a\    ${include_line}" "${NGINX_SITE}"
}

ensure_include_once "include /etc/nginx/snippets/hextyl-cloudflare-realip.conf;"
ensure_include_once "include /etc/nginx/snippets/hextyl-cloudflare-origin-lock.conf;"
ensure_include_once "include /etc/nginx/snippets/hextyl-wings-remote-allow.conf;"

if [[ "${ENABLE_CF_HEADER_GUARD}" == "y" || "${ENABLE_CF_HEADER_GUARD}" == "Y" || "${ENABLE_CF_HEADER_GUARD}" == "1" || "${ENABLE_CF_HEADER_GUARD}" == "true" ]]; then
    cat > "${HEADER_GUARD_SNIPPET}" <<'EOF'
# Auto-generated by lock_origin_to_cloudflare.sh
if ($http_cf_connecting_ip = "") {
    return 444;
}
EOF
    ensure_include_once "include /etc/nginx/snippets/hextyl-cloudflare-header-guard.conf;"
else
    sed -i '\#include /etc/nginx/snippets/hextyl-cloudflare-header-guard.conf;#d' "${NGINX_SITE}" || true
fi

{
    echo "table inet hextyl_cf_origin_lock {"
    echo "    set cf_ipv4 {"
    echo "        type ipv4_addr"
    echo "        elements = {"
    awk 'NF {printf "            %s,\n", $0}' "${CF_V4}" | sed '$ s/,$//'
    echo "        }"
    echo "    }"
    echo "    set cf_ipv6 {"
    echo "        type ipv6_addr"
    echo "        elements = {"
    awk 'NF {printf "            %s,\n", $0}' "${CF_V6}" | sed '$ s/,$//'
    echo "        }"
    echo "    }"
    echo "    chain input_lock {"
    echo "        type filter hook input priority -151; policy accept;"
    echo "        iifname \"lo\" accept"
    echo "        tcp dport { 80, 443 } ip saddr @cf_ipv4 accept"
    echo "        tcp dport { 80, 443 } ip6 saddr @cf_ipv6 accept"
    if [[ -n "${EXTRA_ALLOW_CSV}" ]]; then
        IFS=',' read -r -a extra_nft <<< "${EXTRA_ALLOW_CSV}"
        for entry in "${extra_nft[@]}"; do
            entry="$(echo "${entry}" | xargs)"
            [[ -n "${entry}" ]] || continue
            if [[ "${entry}" == *:* ]]; then
                echo "        tcp dport { 80, 443 } ip6 saddr ${entry} accept"
            else
                echo "        tcp dport { 80, 443 } ip saddr ${entry} accept"
            fi
        done
    fi
    echo "        tcp dport { 80, 443 } drop"
    echo "    }"
    echo "}"
} > "${NFT_LOCK_FILE}"

if [[ -f /etc/nftables.conf ]] && ! grep -q 'include "/etc/nftables.d/\*.nft"' /etc/nftables.conf; then
    printf '\ninclude "/etc/nftables.d/*.nft"\n' >> /etc/nftables.conf
fi

log "Applying nftables Cloudflare origin lock..."
nft flush table inet hextyl_cf_origin_lock >/dev/null 2>&1 || true
nft -f "${NFT_LOCK_FILE}"

log "Testing and reloading nginx..."
nginx -t
systemctl reload nginx

log "Cloudflare-only origin lock is active."
echo "      Nginx site: ${NGINX_SITE}"
echo "      RealIP:     ${REALIP_SNIPPET}"
echo "      Allowlist:  ${ORIGIN_LOCK_SNIPPET}"
echo "      WingsAllow: ${WINGS_REMOTE_SNIPPET}"
echo "      HeaderGuard:${HEADER_GUARD_SNIPPET} (enabled=${ENABLE_CF_HEADER_GUARD})"
echo "      NFT file:   ${NFT_LOCK_FILE}"
